<?php

/**
 * @file
 * LocalGov Drupal news article module file.
 */

/**
 * Implements hook_theme().
 */
function localgov_news_theme($existing, $type, $theme, $path) {
  return [
    'node__localgov_news_article__teaser' => [
      'template' => 'node--localgov-news-article--teaser',
      'base hook' => 'node',
    ],
    'node__localgov_news_article__full' => [
      'template' => 'node--localgov-news-article--full',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_tokens_alter().
 * Needed to correctly render schema metadata for categories containing commas
 */
function localgov_news_tokens_alter(&$replacements, $context) {
  // Remove commas in news categories so they are not split.
  if ($context['type'] == 'node') {
    if (isset($replacements['[node:localgov_news_categories:0:entity]'])) {
      $replacements['[node:localgov_news_categories:0:entity]'] = stripslashes(str_replace(',', '', $replacements['[node:localgov_news_categories:0:entity]']));
    }
  }
}
