<?php

/**
 * @file
 * LocalGov Drupal News: Newsroom module file.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function localgov_newsroom_theme() {
  return [
    'localgov_featured_news_block' => [
      'variables' => [
        'featured' => [],
      ],
      'render element' => 'block',
      'template' => 'localgov-featured-news-block',
    ],
  ];
}

/**
 * Implements hook_views_query_alter
 */
function localgov_newsroom_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'localgov_news_list') {
    $block_manager = \Drupal::service('plugin.manager.block');
    $block_plugin = $block_manager->createInstance('localgov_featured_news_block');
    $ids = $block_plugin->getDisplayNewsIds();

    if (!empty($ids) && !empty($query->where[1]['conditions'])) {
      $query->where[1]['conditions'][] = [
        'field' => 'node_field_data.nid',
        'value' => $ids,
        'operator' => 'not in',
      ];
    }
  }
}
