<?php

/**
 * @file
 * LocalGov Drupal News: Newsroom module file.
 */

use Drupal\Core\Url;
use Drupal\localgov_newsroom\Newsroom;

/**
 * Implements hook_theme().
 */
function localgov_newsroom_theme() {
  return [
    'localgov_featured_news_block' => [
      'variables' => [
        'featured' => [],
      ],
      'render element' => 'block',
      'template' => 'localgov-featured-news-block',
    ],
    'infinite_scroll' => [
      'render element' => 'block',
      'variables' => [
        'content' => [],
        'totalPerPage' => Newsroom::TOTAL_PER_PAGE,
        'displayShowMore' => TRUE,
        'ajax_callback_route' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_newsroom_preprocess_infinite_scroll(&$variables) {
  $url = Url::fromRoute($variables['ajax_callback_route']);

  $variables['#attached']['library'][] = 'localgov_newsroom/infinite_scroll';
  $variables['#attached']['drupalSettings']['infiniteScroll']['callbackUrl'] = $url->toString();
}
