<?php

/**
 * @file
 * LocalGov Drupal news article module file.
 */

/**
 * Implements hook_theme().
 */
function localgov_news_article_theme($existing, $type, $theme, $path) {
  return [
    'node__localgov_news_article__teaser' => [
      'template' => 'node--localgov-news-article--teaser',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function localgov_news_article_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if (in_array($form_id, ['node_localgov_news_article_form', 'node_localgov_news_article_edit_form'])) {

    // Add our custom summary widget (which should obey the field group on the manage form display)
    $bodyWidget = reset($form['body']['widget']);
    $form['localgov_news_summary'] = $bodyWidget['summary'];
    $form['localgov_news_summary']['#description'] = '<p>'.t('Full sentences and around 160 characters.').'</p>';
    $form ['localgov_news_summary']['#required'] = TRUE;
    unset($form['body']['widget'][0]['summary']);

    // Add our custom submit handler
    $form['actions']['submit']['#submit'][] = '_localgov_news_article_node_form_submit';
  }
}

/**
 * Custom news article submit handler
 * @param  array                                $form
 * @param  \Drupal\Core\Form\FormStateInterface $form_state
 */
function _localgov_news_article_node_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {

  // Get the form values
  $formValues = $form_state->getValues();

  // Set body field to the custom summary field value
  $localgovNewsSummary = $formValues['localgov_news_summary'];
  $body = reset($formValues['body']);
  $body['summary'] = $localgovNewsSummary;

  // Save the modified body field
  $node = $form_state->getFormObject()->getEntity();
  $node->get('body')->setValue($body);

  // Save the node
  $node->save();
}

/**
 * Implements hook_entity_extra_field_info().
 */
function localgov_news_article_entity_extra_field_info() {

  // Add summary pseudo field to form display
  $extra_field['node']['news']['form']['localgov_news_summary'] = [
    'label' => t('Summary'),
    'weight' => 0,
    'visible' => true
  ];

  return $extra_field;
}
